seed: 1234
dist_config:
  dist_backend: "nccl"
  dist_url: "tcp://localhost:54321"
  world_size: 1
path:
  ckpt_path: "/data/yingting/Adapter/output/ckpt/LTS/lts_transformer/lts_finetune"
  log_path: "/data/yingting/Adapter/output/log/LTS/lts_transformer/lts_finetune"
  result_path: "/data/yingting/Adapter/output/result/LTS/lts_transformer/lts_finetune"
optimizer:
  batch_size: 64
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [30000, 40000, 50000]
  anneal_rate: 0.3
loss:
  noise_loss: "l1"
  dur_loss: "mse"
  pitch_loss: "l1"
  cwt_loss: "l1"
  # cwt_add_f0_loss: false
  lambda_f0: 1.0
  lambda_uv: 1.0
  lambda_ph_dur: 1.0
  lambda_word_dur: 0.0 # lambda_word_dur should not be activated, otherwise it will produce NaN value (For VCTK)
  lambda_sent_dur: 1.0
step:
  total_step: 909000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 2500
  var_start_steps: 50000
duration:
  binarization_start_steps: 600
  binarization_loss_enable_steps: 1800
  binarization_loss_warmup_steps: 1000
prosody:
  gmm_mdn_beta: 0.02
  prosody_loss_enable_steps: 100000


